version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    mem_limit: 512m


  # -------------------------------------------------------------------
  # Celery Worker (producer)
  # -------------------------------------------------------------------
  celery_enqueue:
    build: .
    command: celery -A app worker -Q enqueue -P eventlet --concurrency=200 -l info
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
      - postgres
    restart: always

  # -------------------------------------------------------------------
  # Celery Worker (batch flusher)
  # -------------------------------------------------------------------
  celery_flush:
    build: .
    environment:
      - CELERY_QUEUE_NAME=flush
    command: celery -A app worker -Q flush --concurrency=2 -O fair -l info
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
      - postgres
    restart: always

  postgres:
    image: postgres:15                # runs Postgres 13 container
    environment:
      POSTGRES_USER: meter            # creates a DB user "meter"
      POSTGRES_PASSWORD: meterpass    # password for "meter"
      POSTGRES_DB: meterdb            # creates a default DB "meterdb"
    ports:
      - "5432:5432"                   # exposes DB on host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data   # persistent volume
    mem_limit: 1g

  flower:
    build: .
    command: celery -A app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - web
    restart: always


volumes:
  postgres_data:   # named volume for persistence