{
 "title": "Infra Health",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Influx Resource Utilization(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "DbInstanceName": "smart-meter-iot-influxdb" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/Timestream/InfluxDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DbInstanceName": "smart-meter-iot-influxdb" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/Timestream/InfluxDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DbInstanceName": "smart-meter-iot-influxdb" },
     "metricName": "DiskUtilization",
     "namespace": "AWS/Timestream/InfluxDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda invocations, errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "smart-meter-iot-kinesis-to-influx"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "FunctionName": "smart-meter-iot-kinesis-to-influx"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "smart-meter-iot-kinesis-to-influx"
     },
     "label": "p99",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "ap-northeast-1",
     "statistic": "p99"
    },
    {
     "dimensions": {
      "FunctionName": "smart-meter-iot-kinesis-to-influx"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p50"
    },
    {
     "dimensions": {
      "FunctionName": "smart-meter-iot-kinesis-to-influx"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p95"
    }
   ]
  },
  {
   "title": "Kinesis incomingRecords",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "metricName": "IncomingRecords",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "IOT Publish success, throttled count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "metricName": "PublishIn.Success",
     "namespace": "AWS/IoT",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "metricName": "PublishIn.Throttle",
     "namespace": "AWS/IoT",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Kinesis IteratorAge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "metricName": "GetRecords.IteratorAgeMilliseconds",
     "namespace": "AWS/Kinesis",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}