{
 "title": "Ingestion Lag & Throughput",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Lambda Invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "smart-meter-iot-kinesis-to-influx"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Kinesis incoming records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "metricName": "IncomingRecords",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda Duration p99 (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "smart-meter-iot-kinesis-to-influx"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p99"
    }
   ]
  },
  {
   "title": "Kinesis IteratorAge alert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "metricName": "GetRecords.IteratorAgeMilliseconds",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Influx Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "metricName": "WriteThroughput",
     "namespace": "AWS/Timestream/InfluxDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}