# Generated by Django 5.2.6 on 2025-09-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['meter_id', 'timestamp'], name='core_readin_meter_i_f9911f_idx')],
            },
        ),
    ]
